import Head from "next/head";
import { Poppins } from "next/font/google";
import { Button } from "@mantine/core";
import { createStyles, getStylesRef, rem } from "@mantine/core";
import { HeroImageRight } from "@/components/HeroImageRight";
import Banner from "@/components/Banner";
import EmailBanner from "@/components/EmailBanner";
import Crousels from "@/components/Carousels";
import LogosBanner from "@/components/LogosBanner";
import About from "@/components/About";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["300"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Kemptech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroImageRight />
        <LogosBanner />
        <Crousels />
        <Banner />
        <About />
        <EmailBanner />
      </main>
    </>
  );
}
