import Head from "next/head";
import { Poppins } from "next/font/google";
import { Button } from "@mantine/core";
import { createStyles, getStylesRef, rem } from "@mantine/core";
import { HeroImageRight } from "@/components/HeroImageRight";
import Banner from "@/components/Banner";
import EmailBanner from "@/components/EmailBanner";
import BussinessBanner from "@/components/BussinessBanner";
import Crousels from "@/components/Carousels";
import LogosBanner from "@/components/LogosBanner";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["300"],
});

const infoData = {
  title: "Integrate effortlessly with any technology stack",
  description:
    "Every once in a while, you’ll see a Golbat that’s missing some fangs. This happens when hunger drives it to try biting a Steel-type Pokémon.",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Kemptech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroImageRight />
        <LogosBanner />
        <Crousels />
        <BussinessBanner
          description={infoData.description}
          title={infoData.title}
        />
        <Banner />
        <EmailBanner />
      </main>
    </>
  );
}
